### ISSUE TITLE
appendOnly renders might not be appendOnly

### ISSUE THREAD

**Issue by petersalas** [fixie-ai/ai-jsx#167]
If a component yields two non-append-only frames, the append-only render will not be append-only. The fix is to disable yielding intermediate values from non-append-only streams when processing an AsyncIterator in `renderStream`.

**Comment by NickHeiner** [comment]
Relatedly, is there a reason that `OpenAICompletionModel` needs to both `yield AI.AppendOnlyStream` at the beginning and `return AI.AppendOnlyStream` at the end?

**Comment by petersalas** [comment]
No that's just a convention I landed on vs returning ""
