### ISSUE TITLE
ai-jsx.tsx Throws Error

### ISSUE THREAD

**Issue by benlower** [fixie-ai/ai-jsx#179]
Trying to run `yarn tsx packages/examples/src/bakeoff/reddit-qa/ai-jsx.tsx` and it throws with the below. This is after running `yarn tsx packages/examples/src/bakeoff/reddit-qa/load-articles.mts`.

```
ben@Bens-MacBook-Air ai-jsx % yarn tsx packages/examples/src/bakeoff/reddit-qa/ai-jsx.tsx
/Users/ben/Dropbox/Mac (2)/Documents/GitHub/ai-jsx/packages/examples/src/bakeoff/reddit-qa/ai-jsx.tsx:34
  throw Error('No documents available. Did you run load-articles first?');
        ^


Error: No documents available. Did you run load-articles first?
    at <anonymous> (/Users/ben/Dropbox/Mac (2)/Documents/GitHub/ai-jsx/packages/examples/src/bakeoff/reddit-qa/ai-jsx.tsx:34:9)

Node.js v20.4.0
```

**Comment by NickHeiner** [comment]
Can you try this again after https://github.com/fixie-ai/ai-jsx/pull/193 lands and lmk if you still see it?

**Comment by benlower** [comment]
LGTM. fixed my issue and I like the new command syntax (e.g. demo:reddit) better. thank you!

**Comment by benlower** [comment]
closing as fixed
