### ISSUE TITLE
The text label is a link

### ISSUE THREAD

**Issue by adriatic** [fixie-ai/ai-jsx#531]
<img width="542" alt="image" src="https://github.com/fixie-ai/ai-jsx/assets/2712405/d5a6cdaf-1121-46c3-8a13-9db2b29e1be2">

**Comment by juberti** [comment]
OOC, what does it link to?

**Comment by adriatic** [comment]
This link should be a text field (further explaned by “Your Fixie API 
key) at the moment it is a Link that points nowhere.

Sorry for not providing that explanation already


------ Original Message ------
From "Justin Uberti" ***@***.***>
To "fixie-ai/ai-jsx" ***@***.***>
Cc "Nikolaj Ivancic" ***@***.***>; "Author" 
***@***.***>
Date 1/10/24, 9:10:35 PM
Subject Re: [fixie-ai/ai-jsx] The text label is a link (Issue #531)

**Comment by adriatic** [comment]
My "problem report" is a consequence of not understanding the structure of the API, so what I perceived as text fields are indeed buttons. As some of these buttons do not create any UI changes, I got confused.
